# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

ignored = ["github.com/mock/handler"]

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.7.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/it-chain/bifrost"
  version = "0.1.13"

[[constraint]]
  name = "github.com/it-chain/heimdall"
  version = "0.1.3"

[[constraint]]
  name = "github.com/it-chain/leveldb-wrapper"
  version = "1.1.0"

[[constraint]]
  name = "github.com/it-chain/midgard"
  version = "0.0.4"

[[constraint]]
  name = "github.com/it-chain/sdk"
  version = "0.1.0"

[[constraint]]
  name = "github.com/it-chain/tesseract"
  version = "0.3.1"

[[constraint]]
  name = "github.com/it-chain/yggdrasill"
  version = "0.1.1"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.4.0"

[[constraint]]
  name = "github.com/magiconair/properties"
  version = "1.8.0"

[[constraint]]
  name = "github.com/rs/xid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.6"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  branch = "master"
  name = "github.com/streadway/amqp"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.5.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "go.uber.org/fx"
  version = "1.7.0"

[[constraint]]
  branch = "master"
  name = "github.com/it-chain/iLogger"
