common:
  bootnodeip: 127.0.0.1:4444
  nodeip: 127.0.0.1:4444
  messaging:
    url: amqp://guest:guest@localhost:5672/
txpool:
  timeoutms: 100
  maxtransactionbyte: 1024
  repositorypath: empty
consensus:
  batchtime: 3
  maxtransactions: 100
blockchain:
  repositorypath: empty
peer:
  leaderelection: RAFT
authentication:
  keytype: ECDSA256
  keypath: .it-chain/
icode:
  repositorypath: empty
grpcgateway:
  empty: empty
  ip: 127.0.0.1:13579
