engine:
  seclv: 192
  sigalgo: ECDSA
  logpath: log/it-chain.log
  keypath: ./keystore/peer_keys
  tmppath: .tmp/
  prikeypath: ./keystore/private_key
  mode: solo
  amqp: amqp://guest:guest@localhost:5672/
  bootstrapnodeaddress: ""
txpool:
  timeoutms: 1000
  maxtransactionbyte: 1024
consensus:
  batchtime: 3
  maxtransactions: 100
blockchain:
  genesisconfpath: ./Genesis.conf
peer:
  leaderelection: RAFT
icode:
  repositorypath: empty
grpcgateway:
  address: 127.0.0.1
  port: "5000"
apigateway:
  address: 127.0.0.1
  port: "4000"
docker:
  use: false
  volumename: it-chain-default-volume
  networkname: it-chain-default-network
  networksubnet: 172.88.1.0/8
