engine:
  logpath: log/it-chain.log
  keypath: .it-chain/
  tmppath: .tmp/
  mode: pbft
  amqp: amqp://guest:guest@localhost:5672/
  bootstrapnodeaddress: "127.0.0.1:5555"
txpool:
  timeoutms: 3000
  maxtransactionbyte: 1024
consensus:
  batchtime: 3
  maxtransactions: 100
blockchain:
  genesisconfpath: ./Genesis.conf
peer:
  leaderelection: RAFT
icode:
  repositorypath: empty
grpcgateway:
  address: a.a.a.a
  port: "5000"
apigateway:
  address: a.a.a.a
  port: "4000"
docker:
  use: true
  volumename: it-chain-default-volume
  networkname: it-chain-default-network
  networksubnet: b.b.b.b/24
